# NYC Taxi data in Winter and Summer

Refer to the [Data dictionary](https://www1.nyc.gov/assets/tlc/downloads/pdf/data_dictionary_trip_records_yellow.pdf) to learn more about the columns that have been provided.

In [2]:
import pandas as pd

path = "../../data/taxi.csv"

# Load the csv file into a dataframe
df = pd.read_csv(path)

# Print the dataframe
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2.0,2019-07-15 16:27:53,2019-07-15 16:44:21,3.0,2.02,1.0,N,186,233,1.0,12.0,1.0,0.5,4.08,0.0,0.3,20.38,2.5
1,2.0,2019-07-17 20:26:35,2019-07-17 20:40:09,6.0,1.59,1.0,N,141,161,2.0,10.0,0.5,0.5,0.00,0.0,0.3,13.80,2.5
2,2.0,2019-07-06 16:01:08,2019-07-06 16:10:25,1.0,1.69,1.0,N,246,249,2.0,8.5,0.0,0.5,0.00,0.0,0.3,11.80,2.5
3,1.0,2019-07-18 22:32:23,2019-07-18 22:35:08,1.0,0.90,1.0,N,229,141,1.0,4.5,3.0,0.5,1.65,0.0,0.3,9.95,2.5
4,2.0,2019-07-19 14:54:29,2019-07-19 15:19:08,1.0,4.79,1.0,N,237,107,1.0,19.5,0.0,0.5,5.70,0.0,0.3,28.50,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,2.0,2019-01-18 08:42:15,2019-01-18 08:56:57,1.0,1.18,1.0,N,43,237,1.0,10.0,0.0,0.5,2.16,0.0,0.3,12.96,0.0
196,1.0,2019-01-19 04:34:45,2019-01-19 04:43:44,1.0,2.30,1.0,N,148,234,1.0,9.5,0.5,0.5,2.15,0.0,0.3,12.95,0.0
197,2.0,2019-01-05 10:37:39,2019-01-05 10:42:03,1.0,0.83,1.0,N,237,263,1.0,5.0,0.0,0.5,1.16,0.0,0.3,6.96,0.0
198,2.0,2019-01-23 10:36:29,2019-01-23 10:44:34,2.0,1.12,1.0,N,144,113,2.0,7.0,0.0,0.5,0.00,0.0,0.3,7.80,0.0
199,2.0,2019-01-30 06:55:58,2019-01-30 07:07:02,5.0,2.41,1.0,N,209,107,1.0,10.5,0.0,0.5,1.00,0.0,0.3,12.30,0.0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               200 non-null    float64
 1   tpep_pickup_datetime   200 non-null    str
 2   tpep_dropoff_datetime  200 non-null    str
 3   passenger_count        200 non-null    float64
 4   trip_distance          200 non-null    float64
 5   RatecodeID             200 non-null    float64
 6   store_and_fwd_flag     200 non-null    str
 7   PULocationID           200 non-null    int64
 8   DOLocationID           200 non-null    int64
 9   payment_type           200 non-null    float64
 10  fare_amount            200 non-null    float64
 11  extra                  200 non-null    float64
 12  mta_tax                200 non-null    float64
 13  tip_amount             200 non-null    float64
 14  tolls_amount           200 non-null    float64
 15  improvement_surcharge  200 non-null    float64
 16  total_amount           200 non-null    float64
 17  congestion_surcharge   200 non-null    float64
dtypes: float64(13), int64(2), str(3)
memory usage: 28.3 KB

In [12]:
# Convert the columns that hold datetime values, to Python datetime objects
df["tpep_pickup_datetime"] = pd.to_datetime(df["tpep_pickup_datetime"], format="%Y-%m-%d %H:%M:%S")
df["tpep_dropoff_datetime"] = pd.to_datetime(df["tpep_dropoff_datetime"], format="%Y-%m-%d %H:%M:%S")

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               200 non-null    float64
 1   tpep_pickup_datetime   200 non-null    datetime64[us]
 2   tpep_dropoff_datetime  200 non-null    datetime64[us]
 3   passenger_count        200 non-null    float64
 4   trip_distance          200 non-null    float64
 5   RatecodeID             200 non-null    float64
 6   store_and_fwd_flag     200 non-null    str
 7   PULocationID           200 non-null    int64
 8   DOLocationID           200 non-null    int64
 9   payment_type           200 non-null    float64
 10  fare_amount            200 non-null    float64
 11  extra                  200 non-null    float64
 12  mta_tax                200 non-null    float64
 13  tip_amount             200 non-null    float64
 14  tolls_amount           200 non-null    float64
 15  improvement_surcharge  200 non-null    float64
 16  total_amount           200 non-null    float64
 17  congestion_surcharge   200 non-null    float64
dtypes: datetime64[us](2), float64(13), int64(2), str(1)
memory usage: 28.3 KB

In [ ]:
# Group rows by dropoff datetime on a monthly basis and calculate average tips per month.
df.groupby([pd.Grouper(key="tpep_dropoff_datetime", freq="ME")])[["tip_amount"]].mean()

                       tip_amount
tpep_dropoff_datetime
2019-01-31                 1.9494
2019-02-28                    NaN
2019-03-31                    NaN
2019-04-30                    NaN
2019-05-31                    NaN
2019-06-30                    NaN
2019-07-31                 2.0784

**Do yellow taxi passengers in New York City tip drivers more in the winter or summer?**

This is the question we have to answer by examining, processing and analyzing the data from our dataset.

**NOTE**: It seems that the dataset contains <span style="color:red;">very limited data</span>. No entries exist for the months Feb-Jun of 2019 and there are no entries after June 2019. In short <span style="text-decoration:underline;">data are not available for answering the above question</span>.

Instead, we decided to look for a more appropriate dataset covering the information we need. As such we opted for the 2023 Yello Taxi Trip Data dataset available from the [NYC OpenData site](https://data.cityofnewyork.us/Transportation/2023-Yellow-Taxi-Trip-Data/4b4i-vvec/about_data). Each row in the dataset represents a taxi trip record. The only issue though is the size of this dataset. There are originally 38.3m rows!

Furthermore, the client needs to answer a number of questions for further clarification of the problem:
1. Should the data span a number of years or concentrate on a specific year? 
2. Should we concentrate on a strict definition of the seasons winter and summer i.e. Dec-Feb and Jun-Aug or split the year in two halves and work separately?
3. Is the tip calculated on an absolute basis regardless of the total fare, or perhaps as a relative percentage of the total fare?